#bridge-file-version: #22
#Non-survival item wipe
clear @a[tag=!admin,scores={item_on=0}] structure_void
clear @a[tag=!admin,scores={item_on=0}] structure_block
clear @a[tag=!admin,scores={item_on=0}] jigsaw
clear @a[tag=!admin,scores={item_on=0}] allow
clear @a[tag=!admin,scores={item_on=0}] deny
clear @a[tag=!admin,scores={item_on=0}] bedrock
clear @a[tag=!admin,scores={item_on=0}] bee_nest
clear @a[tag=!admin,scores={item_on=0}] beehive
clear @a[tag=!admin,scores={item_on=0}] command_block
clear @a[tag=!admin,scores={item_on=0}] repeating_command_block
clear @a[tag=!admin,scores={item_on=0}] chain_command_block
clear @a[tag=!admin,scores={item_on=0}] barrier
clear @a[tag=!admin,scores={item_on=0}] border_block
clear @a[tag=!admin,scores={item_on=0}] mob_spawner
clear @a[tag=!admin,scores={item_on=0}] command_block_minecart
clear @a[tag=!admin,scores={item_on=0}] end_portal_frame
#Type clear @a[tag=!admin,scores={item_on=0}] [item] [data] [value] for custom items
#Clear all spawn eggs(case sensetive)
clear @a[tag=!admin,scores={item_on=0}] spawn_egg
clear @a[tag=!admin,scores={item_on=0}] bat_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] bee_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] blaze_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] cat_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] cave_spider_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] chicken_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] cod_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] cow_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] creeper_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] dolphin_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] donkey_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] drowned_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] elder_guardian_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] enderman_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] endermite_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] evoker_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] fox_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] ghast_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] guardian_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] hoglin_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] horse_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] husk_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] llama_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] magma_cube_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] mooshroom_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] mule_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] ocelot_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] panda_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] parrot_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] phantom_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] pig_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] piglin_brute_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] piglin_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] pillager_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] polar_bear_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] pufferfish_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] rabbit_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] ravager_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] salmon_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] sheep_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] shulker_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] silverfish_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] skeleton_horse_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] skeleton_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] slime_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] spider_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] squid_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] stray_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] strider_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] tropical_fish_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] turtle_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] vex_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] vindicator_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] villager_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] wandering_trader_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] witch_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] wither_skeleton_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] wolf_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] zoglin_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] zombie_horse_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] zombie_pigman_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] zombie_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] zombie_villager_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] axolotl_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] glow_squid_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] goat_spawn_egg
clear @a[tag=!admin,scores={item_on=0}] spawn_egg 51