//import all commands
import "../command/src/ban";
import "../command/src/unban";
import "../command/src/invsee";
import "../command/src/copyinv";
import "../command/src/mute";
import "../command/src/unmute";
import "../command/src/summon_npc";
import "../command/src/vanish";
import "../command/src/clearchat";
import "../command/src/fakeleave";
import "../command/src/fakeleave_server";
import "../command/src/lagclear";
import "../command/src/notify";
import "../command/src/worldborder";
import "../command/src/help";
import "../command/src/admin-kit"
import "../command/src/dtban"
import "../command/src/devinfo"
import "../command/src/report";
